(function(){
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function addControls(){
   const row=document.querySelector('.bar .row');if(!row||document.getElementById('adminLogoutBtn'))return;
   const backup=document.createElement('button');backup.textContent='Download Backup';backup.className='green';backup.onclick=downloadBackup;row.appendChild(backup);
   const restore=document.createElement('button');restore.textContent='Restore Backup';restore.className='orange';restore.onclick=()=>document.getElementById('restoreFile').click();row.appendChild(restore);
   const file=document.createElement('input');file.type='file';file.id='restoreFile';file.accept='.json,application/json';file.style.display='none';file.onchange=restoreBackup;row.appendChild(file);
   const logout=document.createElement('button');logout.id='adminLogoutBtn';logout.textContent='Logout';logout.onclick=adminLogout;row.appendChild(logout);
   const clear=document.createElement('button');clear.textContent='Clear Test Data';clear.className='orange';clear.onclick=clearTestData;row.appendChild(clear);
   const box=document.createElement('div');box.className='card';box.innerHTML='<h2>Customer Feedback</h2><div class="scroll"><table><thead><tr><th>Order</th><th>Shop</th><th>Rider</th><th>Delivery</th><th>Issue</th><th>Comment</th><th>Date</th></tr></thead><tbody id="adminFeedback"><tr><td colspan="7">No feedback yet</td></tr></tbody></table></div>';document.getElementById('app')?.appendChild(box);
 }
 function adminLogout(){localStorage.removeItem('tazviko_admin_key');K='';document.getElementById('key').value='';document.getElementById('app').style.display='none';document.getElementById('msg').textContent='Logged out safely.'}
 async function downloadBackup(){if(!K)return alert('Open Dashboard first');try{const r=await fetch('/api/v1/admin/backup',{headers:{'X-Admin-Key':K}});if(!r.ok)throw Error('Backup failed');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.headers.get('Content-Disposition')||'').match(/filename="([^"]+)"/)?.[1]||'tazviko-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}
 async function restoreBackup(ev){const file=ev.target.files?.[0];ev.target.value='';if(!file)return;let backup;try{backup=JSON.parse(await file.text())}catch(e){return alert('Invalid backup file')}if(backup.format!=='TAZVIKO_BACKUP_V1')return alert('This is not a TAZVIKO backup');const confirmWord=prompt('WARNING: Current data will be replaced. Type RESTORE to continue:');if(confirmWord!=='RESTORE')return;try{const out=await api('/admin/restore',{method:'POST',body:JSON.stringify({confirmation:'RESTORE',backup})});alert('Backup restored successfully. '+Object.values(out.restored||{}).reduce((a,b)=>a+b,0)+' records restored. Please login again.');adminLogout()}catch(e){alert('Restore failed: '+e.message)}}
 async function clearTestData(){if(!K)return alert('Open Dashboard first');const word=prompt('This removes test customers, orders, partners, riders and their products. Download a backup first. Type CLEAR TEST DATA:');if(word!=='CLEAR TEST DATA')return;try{await api('/admin/clear-test-data',{method:'POST',body:JSON.stringify({confirmation:word})});alert('Test data cleared. Built-in catalog and coupons were kept.');adminLogout()}catch(e){alert('Clear failed: '+e.message)}}
 async function loadFeedback(){if(!K||document.getElementById('app')?.style.display==='none')return;try{const f=await api('/admin/feedback');const body=document.getElementById('adminFeedback');if(body)body.innerHTML=(f.feedback||[]).map(x=>`<tr><td>${esc(x.order_code)}</td><td>★ ${x.shop_rating}</td><td>★ ${x.rider_rating}</td><td>★ ${x.delivery_rating}</td><td>${esc(x.issue||'—')}</td><td>${esc(x.comment||'—')}</td><td>${esc((x.created_at||'').slice(0,10))}</td></tr>`).join('')||'<tr><td colspan="7">No feedback yet</td></tr>'}catch(e){}}
 addControls();setInterval(loadFeedback,5000);setTimeout(loadFeedback,500);
})();
