(function(){
 const api=async(path,opt={})=>{const token=localStorage.getItem('tazviko_token')||'';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('/api/v1'+path,{headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},signal:controller.signal,...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}catch(e){if(e.name==='AbortError')throw new Error('server_timeout');if(e instanceof TypeError)throw new Error('server_unavailable');throw e}finally{clearTimeout(timer)}};
 let gatewayConfig={online_payment_enabled:false,razorpay_key_id:''};
 function savedCoords(){try{const x=JSON.parse(localStorage.getItem('tazviko_coords')||'null');return x&&Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lng))?{lat:Number(x.lat),lng:Number(x.lng)}:null}catch(e){return null}}
 window.useCustomerLocation=function(){const status=document.getElementById('locationStatus');if(!navigator.geolocation){if(status)status.textContent='Location is not supported on this device.';return}if(status)status.textContent='Location detect ho rahi hai…';navigator.geolocation.getCurrentPosition(pos=>{const coords={lat:pos.coords.latitude,lng:pos.coords.longitude};localStorage.setItem('tazviko_coords',JSON.stringify(coords));const text=document.getElementById('locInput')?.value.trim()||'Current location';localStorage.setItem('tazviko_location',text);document.getElementById('locationLabel').textContent=text;if(status)status.textContent='✓ Location saved.';closeModal('locationModal');loadLiveCatalog();if(typeof loadNearby==='function')loadNearby();notify('Current delivery location saved')},()=>{if(status)status.textContent='Location permission allow karein, phir dobara try karein.'},{enableHighAccuracy:true,timeout:15000,maximumAge:60000})};
 window.saveLocation=function(){const v=document.getElementById('locInput')?.value.trim();if(!v)return;localStorage.setItem('tazviko_location',v);localStorage.removeItem('tazviko_coords');document.getElementById('locationLabel').textContent=v;closeModal('locationModal');loadLiveCatalog();notify('Address saved. Exact nearby shops ke liye Current Location use karein.')};
 window.captureBusinessLocation=function(){const status=document.getElementById('bizLocationStatus');if(!navigator.geolocation){if(status)status.textContent='Location is not supported.';return}if(status)status.textContent='Shop location detect ho rahi hai…';navigator.geolocation.getCurrentPosition(pos=>{document.getElementById('bizLat').value=pos.coords.latitude;document.getElementById('bizLng').value=pos.coords.longitude;if(status)status.textContent='✓ Shop location saved accurately.'},()=>{if(status)status.textContent='Location permission allow karke shop par dobara try karein.'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
 function injectBusinessLocation(){const address=document.getElementById('bizAddress');if(!address||document.getElementById('bizLat'))return;const box=document.createElement('div');box.innerHTML='<input type="hidden" id="bizLat"><input type="hidden" id="bizLng"><button class="btn btn-green" type="button" onclick="captureBusinessLocation()">📍 Save Shop Current Location</button> <span class="muted" id="bizLocationStatus">Required so nearby customers can find this shop.</span>';address.insertAdjacentElement('afterend',box)}
 async function loadConfig(){try{gatewayConfig=await api('/config');}catch(e){}}
 function replaceAccount(){const m=document.getElementById('accountModal');if(!m)return;m.innerHTML=`<div class="modal-box wide"><h3>TAZVIKO Account</h3><div id="authLoggedOut" class="split"><div class="panel"><h4>Login</h4><input class="field" id="loginMobile" placeholder="Mobile number"><input class="field" id="loginPin" type="password" placeholder="4+ digit PIN"><button class="btn btn-primary" onclick="tazLogin()">Login</button></div><div class="panel"><h4>Create account</h4><input class="field" id="regName" placeholder="Name"><input class="field" id="regMobile" placeholder="Mobile number"><input class="field" id="regEmail" placeholder="Email (optional)"><input class="field" id="regPin" type="password" placeholder="Create 4+ digit PIN"><button class="btn btn-primary" onclick="tazRegister()">Create Account</button></div></div><div id="authLoggedIn" class="panel" style="display:none"><h4 id="authName">My Account</h4><div id="authMeta" class="muted"></div><div class="modal-actions" style="margin-top:14px"><button class="btn btn-outline" onclick="tazLogout()">Logout</button></div></div></div>`;refreshAccount();}
 async function refreshAccount(){const out=document.getElementById('authLoggedOut'),inn=document.getElementById('authLoggedIn');if(!out||!inn)return;const token=localStorage.getItem('tazviko_token');if(!token){out.style.display='grid';inn.style.display='none';return}try{const x=await api('/auth/me');out.style.display='none';inn.style.display='block';document.getElementById('authName').textContent='Hello, '+x.user.name;document.getElementById('authMeta').textContent=x.user.mobile+(x.user.email?' • '+x.user.email:'');}catch(e){localStorage.removeItem('tazviko_token');out.style.display='grid';inn.style.display='none'}}
 window.tazRegister=async()=>{try{const x=await api('/auth/register',{method:'POST',body:JSON.stringify({name:regName.value.trim(),mobile:regMobile.value.trim(),email:regEmail.value.trim(),pin:regPin.value})});localStorage.setItem('tazviko_token',x.token);notify('Account created');refreshAccount();}catch(e){notify('Account: '+e.message)}};
 window.tazLogin=async()=>{try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({mobile:loginMobile.value.trim(),pin:loginPin.value})});localStorage.setItem('tazviko_token',x.token);notify('Login successful');refreshAccount();}catch(e){notify('Login failed')}};
 window.tazLogout=()=>{localStorage.removeItem('tazviko_token');notify('Logged out');refreshAccount()};
 function injectCustomerFields(){prefillUser();const address=document.getElementById('pilotAddress');if(address&&!address.value){try{address.value=localStorage.getItem('tazviko_location')||''}catch(e){}}}
 async function prefillUser(){if(!localStorage.getItem('tazviko_token'))return;try{const x=await api('/auth/me');if(window.pilotName)pilotName.value=x.user.name||'';if(window.pilotMobile)pilotMobile.value=x.user.mobile||'';}catch(e){}}
 window.openCart=(function(old){return function(){injectCustomerFields();prefillUser();old();};})(window.openCart);
 function loadRazorpay(){return new Promise((res,rej)=>{if(window.Razorpay)return res();const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
 function clearAfterOrder(code){localStorage.setItem('tazviko_last_order',code);cart=[];discount=0;activeCoupon='';syncCart();closeModal('cartModal');const tr=document.querySelector('#trackingModal h3');if(tr)tr.textContent='Order '+code+' • Live Tracking';openModal('trackingModal')}
 window.placeDemoOrder=async function(){
   if(!cart.length){notify(t('emptyCart'));return}
   const name=(document.getElementById('pilotName')?.value||'').trim();
   const mobile=(document.getElementById('pilotMobile')?.value||'').trim();
   const address=(document.getElementById('pilotAddress')?.value||'').trim();
   const status=document.getElementById('checkoutStatus');
   const showStatus=(message,isError=false)=>{if(!status)return;status.style.display='block';status.style.background=isError?'#ffe9e5':'#e9f8f1';status.style.color=isError?'#a12a16':'#08794e';status.textContent=message};
   if(!name){document.getElementById('pilotName')?.focus();showStatus('Customer name fill karein.',true);return}
   if(!/^\+?[0-9][0-9\s-]{7,14}$/.test(mobile)){document.getElementById('pilotMobile')?.focus();showStatus('Sahi mobile number fill karein.',true);return}
   if(address.length<8){document.getElementById('pilotAddress')?.focus();showStatus('Full delivery address fill karein.',true);return}
   const method=(payMethod==='COD'?'COD':'RAZORPAY');
   if(method==='RAZORPAY'&&!gatewayConfig.online_payment_enabled){notify('Online payment is not active yet. Please choose COD.');return}
   const btn=document.getElementById('placeOrderBtn'); const oldText=btn?btn.textContent:''; if(btn){btn.disabled=true;btn.textContent='Placing COD order...'}showStatus('Order server par save ho raha hai…');
   try{
     const secureItems=cart.map(x=>({name:x.name,merchant:x.merchant,qty:x.qty}));
     const coords=savedCoords();const out=await api('/orders',{method:'POST',body:JSON.stringify({customer_name:name,mobile,address,items:secureItems,payment_method:method,coupon:activeCoupon,customer_latitude:coords?.lat,customer_longitude:coords?.lng})});
     if(method==='COD'){showStatus('COD order '+out.order_code+' successfully placed.');clearAfterOrder(out.order_code);notify('COD order '+out.order_code+' placed successfully');return}
     const p=await api('/payments/create',{method:'POST',body:JSON.stringify({order_code:out.order_code})});await loadRazorpay();
     const rz=new Razorpay({key:p.key_id,amount:p.amount,currency:'INR',name:'TAZVIKO',description:'Order '+out.order_code,order_id:p.razorpay_order_id,prefill:{name,contact:mobile},handler:async function(resp){try{await api('/payments/verify',{method:'POST',body:JSON.stringify({order_code:out.order_code,...resp})});clearAfterOrder(out.order_code);notify('Payment successful • '+out.order_code);}catch(e){notify('Payment verification failed')}}});rz.open();
   }catch(e){const message=e.message==='server_unavailable'?'Server connect nahi ho raha. Render wali live URL kholen; GitHub preview se COD save nahi hoga.':e.message==='server_timeout'?'Server start hone mein time lag raha hai. 20 seconds baad dobara try karein.':'Order failed: '+e.message;showStatus(message,true);notify(message)}finally{if(btn){btn.disabled=false;btn.textContent=oldText||'Place COD Order'}}
 };
 window.submitPartner=async function(){const val=id=>(document.getElementById(id)?.value||'').trim();const n=val('bizName'),phone=val('bizPhone'),city=val('bizCity'),type=val('bizType'),lat=Number(val('bizLat')),lng=Number(val('bizLng'));if(!n){document.getElementById('bizName')?.focus();notify('Business name required hai');return}if(phone.replace(/\D/g,'').length<8){document.getElementById('bizPhone')?.focus();notify('Sahi owner mobile number required hai');return}if(!Number.isFinite(lat)||!Number.isFinite(lng)||(!lat&&!lng)){notify('Save Shop Current Location par click karna required hai');return}if(!document.getElementById('partnerAgree')?.checked){notify('Please accept partner terms');return}const payload={business_name:n,business_type:type,city,owner_name:val('ownerName'),address:val('bizAddress'),phone:phone.replace(/[\s-]/g,''),bank_ref:[val('bizBank'),val('bizIfsc')].filter(Boolean).join(' / '),catalog:val('bizCatalog'),opening_hours:val('bizHours'),latitude:lat,longitude:lng,kyc:[val('bizGstin'),val('bizLicense'),val('bizPan')].filter(Boolean).join(' / ')};try{const out=await api('/partners/applications',{method:'POST',body:JSON.stringify(payload)});closeModal('partnerModal');notify('Application #'+out.id+' admin approval ke liye submit ho gayi');}catch(e){notify('Application failed: '+e.message)}};
 function escHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 async function loadLiveCatalog(){const grid=document.getElementById('liveCatalogGrid');if(!grid)return;try{const c=savedCoords(),query=c?'?lat='+encodeURIComponent(c.lat)+'&lng='+encodeURIComponent(c.lng):'';const out=await api('/catalog'+query);const rows=(out.products||[]).filter(x=>x.partner_id);grid.innerHTML=rows.length?rows.map(x=>`<div class="card" data-name="${escHtml(x.name+' '+x.merchant+' '+(x.category||''))}" data-type="store" data-rating="5" data-time="30" data-price="${Number(x.price)||0}"><div class="thumb" style="${x.image_url?`background-image:url('${escHtml(x.image_url)}');background-size:cover;background-position:center`:''}">${x.image_url?'':'🛍️'}<span class="tag">${x.distance_km!=null?escHtml(x.distance_km)+' km • ':''}In stock: ${Number(x.stock_qty)||0}</span></div><div class="card-body"><h3>${escHtml(x.name)}</h3><div class="meta">${escHtml(x.merchant)} • ${escHtml(x.category||'Product')}</div><div class="price-row"><span class="price">₹${Number(x.price)||0}</span><button class="add" onclick="addToCart(decodeURIComponent('${encodeURIComponent(x.name)}'),${Number(x.price)||0},decodeURIComponent('${encodeURIComponent(x.merchant)}'))">ADD</button></div></div></div>`).join(''):`<div class="muted">${c?'Aapki location par abhi koi approved TAZVIKO shop delivery range mein nahi hai.':'Nearby shops dekhne ke liye “Use My Current Location” click karein.'}</div>`}catch(e){grid.innerHTML='<div class="muted">Partner catalog अभी load nahi ho paya.</div>'}}
 async function refreshTracking(){const code=localStorage.getItem('tazviko_last_order');if(!code)return;try{const x=await api('/orders/'+encodeURIComponent(code)+'/tracking');const tr=document.querySelector('#trackingModal h3');if(tr)tr.textContent='Order '+x.order_code+' • '+x.status.replaceAll('_',' ');const b=document.getElementById('trackingBody');if(b){let feedback='';if(x.status==='DELIVERED'&&!x.feedback_submitted)feedback=`<hr><h4>Rate Your Order</h4><input class="field" id="feedbackMobile" inputmode="numeric" placeholder="Order mobile number" value="${escHtml(document.getElementById('pilotMobile')?.value||'')}"><div class="row3"><select class="field" id="shopRating"><option value="">Shop rating</option>${[5,4,3,2,1].map(v=>`<option value="${v}">${v} Star</option>`).join('')}</select><select class="field" id="riderRating"><option value="">Rider rating</option>${[5,4,3,2,1].map(v=>`<option value="${v}">${v} Star</option>`).join('')}</select><select class="field" id="deliveryRating"><option value="">Delivery rating</option>${[5,4,3,2,1].map(v=>`<option value="${v}">${v} Star</option>`).join('')}</select></div><select class="field" id="feedbackIssue"><option value="">No issue</option><option>Late delivery</option><option>Wrong item</option><option>Damaged item</option><option>Missing item</option><option>Other</option></select><textarea class="field" id="feedbackComment" placeholder="Comment (optional)"></textarea><button class="btn btn-primary" onclick="submitOrderFeedback()">Submit Feedback</button>`;else if(x.feedback_submitted)feedback='<hr><b>✓ Feedback submitted. Thank you!</b>';b.innerHTML='<b>Status:</b> '+x.status.replaceAll('_',' ')+'<br><b>Payment:</b> '+x.payment_method+' / '+x.payment_status+'<br><b>Total:</b> ₹'+x.total+'<br><span class="muted">Last updated from the TAZVIKO server.</span>'+feedback;}}catch(e){}}
 window.submitOrderFeedback=async function(){const code=localStorage.getItem('tazviko_last_order');const payload={mobile:(document.getElementById('feedbackMobile')?.value||'').trim(),shop_rating:Number(document.getElementById('shopRating')?.value),rider_rating:Number(document.getElementById('riderRating')?.value),delivery_rating:Number(document.getElementById('deliveryRating')?.value),issue:document.getElementById('feedbackIssue')?.value||'',comment:(document.getElementById('feedbackComment')?.value||'').trim()};if(!payload.shop_rating||!payload.rider_rating||!payload.delivery_rating){notify('Teenon ratings select karein');return}try{await api('/orders/'+encodeURIComponent(code)+'/feedback',{method:'POST',body:JSON.stringify(payload)});notify('Feedback submit ho gaya. Thank you!');await refreshTracking()}catch(e){notify('Feedback: '+e.message)}};
 async function refreshQuoteUI(){
   if(!cart.length)return updateCartUI();
   try{
     const secureItems=cart.map(x=>({name:x.name,merchant:x.merchant,qty:x.qty}));
     const q=await api('/quote',{method:'POST',body:JSON.stringify({items:secureItems,coupon:activeCoupon})});
     discount=q.discount||0; deliveryFeeAmt=q.delivery_fee||0;
     document.getElementById('subTotal').textContent='₹'+q.subtotal;
     document.getElementById('discount').textContent='-₹'+q.discount;
     document.getElementById('delivery').textContent='₹'+q.delivery_fee;
     document.getElementById('platform').textContent='₹'+q.platform_fee;
     document.getElementById('tax').textContent='₹'+q.tax;
     document.getElementById('grandTotal').textContent='₹'+q.total;
   }catch(e){}
 }
 window.applyCoupon=async function(){
   const code=document.getElementById('couponInput').value.trim().toUpperCase();
   if(!cart.length){notify(t('emptyCart'));return}
   try{const secureItems=cart.map(x=>({name:x.name,merchant:x.merchant,qty:x.qty}));const q=await api('/quote',{method:'POST',body:JSON.stringify({items:secureItems,coupon:code})});if(!q.coupon){activeCoupon='';notify('Coupon not applicable');}else{activeCoupon=q.coupon;notify('Coupon '+q.coupon+' applied');}await refreshQuoteUI();}catch(e){notify('Coupon: '+e.message)}
 };
 window.submitSupportTicket=async function(){
   const message=(document.getElementById('supportMessage')?.value||'').trim(); if(!message){notify('Please enter your support message');return}
   try{const x=await api('/support/tickets',{method:'POST',body:JSON.stringify({category:document.getElementById('supportCategory').value,mobile:document.getElementById('supportMobile').value.trim(),message})});document.getElementById('supportMessage').value='';closeModal('supportModal');notify('Support ticket #'+x.ticket_id+' created');}catch(e){notify('Support: '+e.message)}
 };
 window.submitDeliveryPartner=async function(){
   const full_name=deliveryName.value.trim(),mobile=deliveryMobile.value.trim(); if(!full_name||!mobile){notify('Name and mobile are required');return}
   try{await api('/delivery/applications',{method:'POST',body:JSON.stringify({full_name,mobile,vehicle_type:deliveryVehicleType.value,vehicle_number:deliveryVehicleNumber.value.trim(),identity_ref:deliveryIdentity.value.trim(),payout_ref:deliveryPayout.value.trim()})});closeModal('deliveryPartnerModal');notify('Delivery partner application submitted for review');}catch(e){notify('Application: '+e.message)}
 };
 async function loadMyOrders(){const box=document.getElementById('realOrdersList');if(!box)return;if(!localStorage.getItem('tazviko_token')){box.innerHTML='<div class="muted">Login to view your orders.</div>';return}try{const x=await api('/orders/mine');box.innerHTML=x.orders.length?x.orders.map(o=>`<div class="list-item"><div><b>${o.order_code} • ${o.merchant||'TAZVIKO'}</b><div class="muted">₹${o.total} • ${o.payment_status} • ${o.status}</div></div><button class="btn btn-primary" onclick="trackSpecificOrder('${o.order_code}')">Track</button></div>`).join(''):'<div class="muted">No orders yet.</div>';}catch(e){box.innerHTML='<div class="muted">Please login again to view orders.</div>'}}
 window.trackSpecificOrder=async function(code){localStorage.setItem('tazviko_last_order',code);await refreshTracking();openModal('trackingModal')};
 const originalOpenModal=window.openModal; window.openModal=function(id){if(id==='ordersModal')loadMyOrders();return originalOpenModal(id)};
 async function initLaunch(){await loadConfig();replaceAccount();injectCustomerFields();injectBusinessLocation();loadLiveCatalog();if(!savedCoords())setTimeout(()=>openModal('locationModal'),800);document.querySelectorAll('[data-online-pay]').forEach(el=>{if(!gatewayConfig.online_payment_enabled){el.style.opacity='.45';el.title='Online payment will be enabled after payment KYC/setup';}});payMethod='COD';const cod=document.getElementById('codPayOption');if(cod)selectPay(cod,'COD');const orderButton=document.getElementById('placeOrderBtn');if(orderButton){orderButton.onclick=null;orderButton.addEventListener('click',event=>{event.preventDefault();window.placeDemoOrder()});}setInterval(refreshTracking,8000);refreshTracking();const badge=document.createElement('div');badge.style.cssText='position:fixed;bottom:16px;left:16px;z-index:80;background:#172033;color:#fff;padding:9px 12px;border-radius:999px;font:700 12px system-ui;box-shadow:0 8px 24px #0002';badge.textContent=gatewayConfig.online_payment_enabled?'● TAZVIKO Live • COD + Online':'● TAZVIKO Live • COD';document.body.appendChild(badge);}
 initLaunch();
})();
