-- TAZVIKO starter relational schema (PostgreSQL-oriented)
CREATE TABLE users (id bigserial PRIMARY KEY, role varchar(30) NOT NULL, mobile varchar(20) UNIQUE, email varchar(255), name varchar(150), status varchar(30) DEFAULT 'active', created_at timestamptz DEFAULT now());
CREATE TABLE addresses (id bigserial PRIMARY KEY, user_id bigint REFERENCES users(id), label varchar(50), address_text text NOT NULL, lat numeric(10,7), lng numeric(10,7), is_default boolean DEFAULT false);
CREATE TABLE merchants (id bigserial PRIMARY KEY, owner_user_id bigint REFERENCES users(id), business_name varchar(200) NOT NULL, type varchar(40) NOT NULL, status varchar(30) DEFAULT 'pending', gstin varchar(20), fssai varchar(30), commission_pct numeric(5,2), created_at timestamptz DEFAULT now());
CREATE TABLE merchant_branches (id bigserial PRIMARY KEY, merchant_id bigint REFERENCES merchants(id), name varchar(150), address_text text, lat numeric(10,7), lng numeric(10,7), open_status boolean DEFAULT true);
CREATE TABLE products (id bigserial PRIMARY KEY, merchant_id bigint REFERENCES merchants(id), name varchar(200) NOT NULL, category varchar(100), price numeric(12,2) NOT NULL, tax_pct numeric(5,2) DEFAULT 0, available boolean DEFAULT true, stock_qty numeric(12,3), image_url text);
CREATE TABLE orders (id bigserial PRIMARY KEY, customer_user_id bigint REFERENCES users(id), merchant_id bigint REFERENCES merchants(id), status varchar(30) NOT NULL, payment_status varchar(30), subtotal numeric(12,2), discount numeric(12,2), tax numeric(12,2), delivery_fee numeric(12,2), platform_fee numeric(12,2), grand_total numeric(12,2), platform_commission numeric(12,2), merchant_payable numeric(12,2), created_at timestamptz DEFAULT now());
CREATE TABLE order_items (id bigserial PRIMARY KEY, order_id bigint REFERENCES orders(id), product_id bigint REFERENCES products(id), name_snapshot varchar(200), qty numeric(12,3), unit_price numeric(12,2), line_total numeric(12,2));
CREATE TABLE payments (id bigserial PRIMARY KEY, order_id bigint REFERENCES orders(id), provider varchar(30), provider_payment_id varchar(150), method varchar(30), amount numeric(12,2), status varchar(30), created_at timestamptz DEFAULT now());
CREATE TABLE payouts (id bigserial PRIMARY KEY, merchant_id bigint REFERENCES merchants(id), period_from date, period_to date, gross_amount numeric(12,2), deductions numeric(12,2), net_amount numeric(12,2), status varchar(30), provider_payout_id varchar(150));
CREATE TABLE riders (id bigserial PRIMARY KEY, user_id bigint REFERENCES users(id), status varchar(30), vehicle_type varchar(50), current_lat numeric(10,7), current_lng numeric(10,7));
CREATE TABLE deliveries (id bigserial PRIMARY KEY, order_id bigint REFERENCES orders(id), rider_id bigint REFERENCES riders(id), status varchar(30), assigned_at timestamptz, picked_at timestamptz, delivered_at timestamptz);
CREATE TABLE coupons (id bigserial PRIMARY KEY, code varchar(60) UNIQUE, discount_type varchar(30), discount_value numeric(12,2), max_discount numeric(12,2), min_order numeric(12,2), active boolean DEFAULT true);
CREATE TABLE support_tickets (id bigserial PRIMARY KEY, user_id bigint REFERENCES users(id), order_id bigint REFERENCES orders(id), category varchar(80), message text, status varchar(30) DEFAULT 'open', created_at timestamptz DEFAULT now());
